ame_health/urls.py
from django.urls import path, include
from django.contrib import admin
app_name = 'ame_health'

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('core.urls', namespace='core')),
    path('vaga/', include('vaga.urls', namespace='vaga')),
    path('pessoa/', include('pessoa.urls', namespace='pessoa')),

]

core/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from core.views import *
app_name = 'core'


urlpatterns = [
    path('', HomeListView.as_view(), name='home'),

    path('perfil/', PerfilTemplateView.as_view(), name='perfil'),
    path('logout/', LogoutView.as_view(next_page='core:home'), name='logout'),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),

    path('cadastro_gestor/', CadastroGestorCreateView.as_view(), name='cadastro_gestor'),
    path('update_gestor/', UpdateGestorUpdateView.as_view(), name='update_gestor'),
    path('update_password_gestor/', UpdatePasswordGestorFormVieW.as_view(), name='update_password_gestor'),
    path('vagas_candidato/', VagaCandidatoListView.as_view(), name='vagas_candidato'),
    path('curriculo_candidato/', CurriculoCandidatoListView.as_view(), name='curriculo_candidato'),
    path('new_curriculo/', NovoCurriculoCreateView.as_view(), name='new_curriculo'),

    path('cadastro_candidato/', CadastroCandidatoCreateView.as_view(), name='cadastro_candidato'),
    path('update_candidato/', UpdateCandidatoUpdateView.as_view(), name='update_candidato'),
    path('update_password_candidato/', UpdatePasswordCandidatoFormVieW.as_view(), name='update_password_candidato'),
    path('vagas_gestor/', VagasGestorCreateView.as_view(), name='vagas_gestor'),

]

pessoa/urls.py
from django.conf.urls import url, include
from pessoa.models import User
from pessoa.views import PessoaView
from rest_framework import routers, serializers, viewsets

# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('title', 'state', 'city', 'enterprise', 'description', 'dt_validate')

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)


app_name = 'pessoa'

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    url('', include(router.urls)),
    url('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url('rest_pessoas/', PessoaView.as_view(), name='rest_pessoas')
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from pessoa.forms import UserAdminCreationForm
from django.urls import reverse_lazy
from vaga.models import VagaModel
from vaga.forms import VagaForm
from pessoa.forms import CurriculoForm
from pessoa.models import User, CurriculoModel


# Create your views here.
class HomeListView(ListView):
    model = VagaModel
    # paginate_by = 5
    template_name = 'core/index.html'

# CANDIDATO VIEW ###################################################################
class CadastroCandidatoCreateView(CreateView):
    model = User
    template_name = 'core/cadastro_candidato.html'
    form_class = UserAdminCreationForm
    success_url = reverse_lazy('core:perfil')


class UpdateCandidatoUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'core/update_candidato.html'
    fields = ['name', 'email', 'cpf']
    success_url = reverse_lazy('core:perfil')

    def get_object(self):
        return self.request.user


class UpdatePasswordCandidatoFormVieW(LoginRequiredMixin, FormView):
    template_name = 'core/update_password_candidato.html'
    success_url = reverse_lazy('core:perfil')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordCandidatoFormVieW, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class VagaCandidatoListView(ListView):
    model = VagaModel
    # paginate_by = 5
    template_name = 'core/gerenciar_vagas_candidato.html'


class CurriculoCandidatoListView(ListView):
    model = CurriculoModel
    template_name = 'core/curriculo_candidato.html'


class NovoCurriculoCreateView(LoginRequiredMixin, FormView):
    form_class = CurriculoForm
    template_name = 'core/novo_curriculo.html'
    success_url = reverse_lazy('core:perfil')

    def form_valid(self, form):
        print(self.request.user)
        curriculo = form.save(commit=False)
        curriculo.author = self.request.user
        form.save()
        return super(NovoCurriculoCreateView, self).form_valid(form)


# GESTOR VIEW ###################################################################
class CadastroGestorCreateView(LoginRequiredMixin, CreateView):
    form_class = UserAdminCreationForm
    template_name = 'core/cadastro_gestor.html'

    def get_object(self):
        return self.request.user


class UpdateGestorUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = 'core/update_gestor.html'
    fields = ['name', 'email', 'cpf', 'type']
    success_url = reverse_lazy('core:perfil')

    def get_object(self):
        return self.request.user


class UpdatePasswordGestorFormVieW(LoginRequiredMixin, FormView):
    template_name = 'core/update_password_gestor.html'
    success_url = reverse_lazy('core:perfil')
    form_class = PasswordChangeForm

    def get_form_kwargs(self):
        kwargs = super(UpdatePasswordGestorFormVieW, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class VagasGestorCreateView(LoginRequiredMixin, FormView):
    form_class = VagaForm
    template_name = 'core/gerenciar_vagas_gestor.html'
    success_url = reverse_lazy('core:perfil')

    def form_valid(self, form):
        vaga = form.save(commit=False)
        vaga.author = self.request.user
        form.save()
        return super(VagasGestorCreateView, self).form_valid(form)


class VagaListView(ListView):
    model = VagaModel
    template_name = 'core/vaga_page.html'


    def get_queryset(self, *args, **kwargs):
        return VagaModel.objects.filter(slug=self.kwargs['slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(VagaListView, self).get_context_data(**kwargs)
        context['vaga'] = get_object_or_404(VagaModel, slug=self.kwargs['slug'])
        return context


# GERAL ###################################################################
class PerfilTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'core/perfil.html'

core/templates/core/cadastro_gestor.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_gestor_content %}
<li class="breadcrumb-item active" aria-current="page">Cadastrar Pessoa</li>
{% endblock %}

{% block breadcrumb_perfil_gestor_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_gestor' %}" class="list-group-item">Gerenciar Vagas</a>
<a href="{% url 'core:update_gestor' %}" class="list-group-item">Alterar Dados</a>
<a href="{% url 'core:update_password_gestor' %}" class="list-group-item">Alterar Senha</a>
<a href="{% url 'core:cadastro_gestor' %}" class="list-group-item active" aria-current="page">Cadastrar Pessoa</a>
{% endblock %}

{% block perfil_gestor_content %}
{% if user.is_authenticated and user.type == 'Gestor' %}
<div class="row">
  <div class="col-md-10">
    <h2>Cadastrar Pessoa</h2>
  </div>
  <div class="col-md-2" align="center">
    <a href="{% url 'pessoa:rest_pessoas' %}" class="btn btn-info">VIA API REST</a>
  </div>
</div>
<div>
  <form class="form-group" method="POST">
    {% csrf_token %}
    <fieldset>
      <hr>
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% endfor %} 
      </div>
      <button type="submit" class="btn btn-outline-info">Submit</button>
    </fieldset>
  </form>
</div>
{% endif %}  
{% endblock %}

core/templates/core/gerenciar_vagas_candidato.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_candidato_content %}
<li class="breadcrumb-item active" aria-current="page">Gerenciar Vagas</li>
{% endblock %}

{% block breadcrumb_perfil_candidato_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_candidato' %}" class="list-group-item active" aria-current="page"">Gerenciar Vagas</a>
<a href="{% url 'core:update_candidato' %}" class="list-group-item">Alterar Dados</a>
<a href="{% url 'core:update_password_candidato' %}" class="list-group-item">Alterar Senha</a>
<a href="{% url 'core:curriculo_candidato' %}" class="list-group-item">Currículo</a>
{% endblock %}

{% block perfil_candidato_content %}
<h2>Gerenciar Vagas</h2>
<hr>

<div>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
{% endblock %}

core/templates/core/login.html
{% extends "core/base_view.html" %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="content-inside">
	<div id="login">
		<form method="POST">
			{% csrf_token %}
			{% for error in form.non_field_errors %}
		    <div class="alert alert-warning">{{ error }}</div>
		    {% endfor %}
			<fieldset>
			  <div class="form-group">
			    <label for="{{ form.username.auto_id }}">{{ form.username.label }}</label>
			    {% render_field form.username class="form-control" %}
			    <small id="emailHelp" class="form-text text-muted">We'll never share your data with anyone else.</small>
			    {% for error in form.username.errors %}
			    <span class="help-block">{{ error }}</span>
			    {% endfor %}
			  </div>
			  <div class="form-group">
			    <label for="{{ form.password.auto_id }}">{{ form.password.label }}</label>
			    {% render_field form.password class="form-control" %}
			    {% for error in form.password.errors %}
			    <span class="help-block">{{ error }}</span>
			    {% endfor %}
			  </div>
			  <div class="form-group form-check">
			    <input type="checkbox" class="form-check-input" id="rememberuser">
			    <label class="form-check-label" for="rememberuser">Remember me</label>
			  </div>
			  <button type="submit" class="btn btn-success">Submit</button>
			</fieldset>
		</form>
	</div>
</div>
{% endblock %}

core/templates/core/novo_curriculo.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_candidato_content %}
<li class="breadcrumb-item active" aria-current="page">Novo Currículo</li>
{% endblock %}

{% block breadcrumb_perfil_candidato_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_candidato' %}" class="list-group-item" aria-current="page">Gerenciar Vagas</a>
<a href="{% url 'core:update_candidato' %}" class="list-group-item">Alterar Dados</a>
<a href="{% url 'core:update_password_candidato' %}" class="list-group-item">Alterar Senha</a>
<a href="{% url 'core:curriculo_candidato' %}" class="list-group-item active" aria-current="page">Currículo</a>
{% endblock %}

{% block perfil_candidato_content %}
<h2>Novo Currículo</h2>
<hr>
<div>
  <form class="form-group" method="POST">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      {% endfor %} 
      </div>
      <button type="submit" class="btn btn-outline-info">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

core/templates/core/perfil.html
{% extends "core/base_view.html" %}
{% load static %}

{% block content %}
{% if user.is_authenticated and user.type == 'Candidato' or user.type == '' %}
<div id="perfil-candidato">
	<div class="row">
		<div class="col-md-12">
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			    <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
			    {% block title_perfil_candidato_content %}
			    <li class="breadcrumb-item active" aria-current="page">Minha Conta</li>
			    {% endblock %}
			  </ol>
			</nav>
		</div>
	</div>
	<!-- fim da row -->

	<div class="row">
		<div class="col-md-3">
            <div class="list-group">
            	{% block breadcrumb_perfil_candidato_content %}
	            <a href="{% url 'core:perfil' %}" class="list-group-item active">Minha Conta</a>
	            <a href="{% url 'core:vagas_candidato' %}" class="list-group-item">Gerenciar Vagas</a>
	            <a href="{% url 'core:update_candidato' %}" class="list-group-item">Alterar Dados</a>
	            <a href="{% url 'core:update_password_candidato' %}" class="list-group-item">Alterar Senha</a>
	            <a href="{% url 'core:curriculo_candidato' %}" class="list-group-item">Currículo</a>
			    {% endblock %}
            </div>
        </div>
        <div class="col-md-9">
        	{% block perfil_candidato_content %}
            <h2 class="minha-conta">Bem vindo(a), {{user.name}}!</h2>
            <hr>

            <div>
            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            	
            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>

        	{% endblock %}
        </div>
	</div>
	<!-- fim da row -->
</div>
{% elif user.is_authenticated and user.type == 'Gestor' %}
<div id="perfil-gestor">
	<div class="row">
		<div class="col-md-12">
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			    <li class="breadcrumb-item"><a href="{% url 'core:home' %}">Home</a></li>
			    {% block title_perfil_gestor_content %}
			    <li class="breadcrumb-item active" aria-current="page">Minha Conta</li>
			    {% endblock %}
			  </ol>
			</nav>
		</div>
	</div>
	<!-- fim da row -->

	<div class="row">
		<div class="col-md-3">
            <div class="list-group">
            	{% block breadcrumb_perfil_gestor_content %}
	            <a href="{% url 'core:perfil' %}" class="list-group-item active">Minha Conta</a>
	            <a href="{% url 'core:vagas_gestor' %}" class="list-group-item">Gerenciar Vagas</a>
	            <a href="{% url 'core:update_gestor' %}" class="list-group-item">Alterar Dados</a>
	            <a href="{% url 'core:update_password_gestor' %}" class="list-group-item">Alterar Senha</a>
	            <a href="{% url 'core:cadastro_gestor' %}" class="list-group-item">Cadastrar Pessoa</a>
			    {% endblock %}
            </div>
        </div>
        <div class="col-md-9">
        	{% block perfil_gestor_content %}
            <h2 class="minha-conta">Bem vindo(a), {{user.name}}!</h2>
            <hr>

            <div>
            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            	
            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
            	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
            	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
            	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
            	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
            	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
            </div>

        	{% endblock %}
        </div>
	</div>
	<!-- fim da row -->
</div>
{% else  %}
<div class="content-inside">
	  <div>
		<a class="btn btn-outline-info btn-lg btn-block" href="{% url 'core:login' %}">Você está deslogado. Realizar login?</a>
	  </div>
</div>
{% endif %}
{% endblock %}

core/templates/core/update_candidato.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_candidato_content %}
<li class="breadcrumb-item active" aria-current="page">Alterar Dados</li>
{% endblock %}

{% block breadcrumb_perfil_candidato_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_candidato' %}" class="list-group-item">Gerenciar Vagas</a>
<a href="{% url 'core:update_candidato' %}" class="list-group-item active">Alterar Dados</a>
<a href="{% url 'core:update_password_candidato' %}" class="list-group-item" aria-current="page">Alterar Senha</a>
<a href="{% url 'core:curriculo_candidato' %}" class="list-group-item">Currículo</a>
{% endblock %}

{% block perfil_candidato_content %}
<h2>Alterar Dados</h2>
<hr>
<div>
  <form class="form-group" method="POST">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% endfor %} 
      </div>
      <button type="submit" class="btn btn-outline-info">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

core/templates/core/update_gestor.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_gestor_content %}
<li class="breadcrumb-item active" aria-current="page">Alterar Dados</li>
{% endblock %}

{% block breadcrumb_perfil_gestor_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_gestor' %}" class="list-group-item">Gerenciar Vagas</a>
<a href="{% url 'core:update_gestor' %}" class="list-group-item active" aria-current="page">Alterar Dados</a>
<a href="{% url 'core:update_password_gestor' %}" class="list-group-item">Alterar Senha</a>
<a href="{% url 'core:cadastro_gestor' %}" class="list-group-item">Cadastrar Pessoa</a>
{% endblock %}

{% block perfil_gestor_content %}
<h2>Alterar Dados</h2>
<hr>
<div>
  <form class="form-group" method="POST">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% endfor %} 
      </div>
      <button type="submit" class="btn btn-outline-info">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

core/templates/core/update_password_candidato.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_candidato_content %}
<li class="breadcrumb-item active" aria-current="page">Alterar Senha</li>
{% endblock %}

{% block breadcrumb_perfil_candidato_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_candidato' %}" class="list-group-item">Gerenciar Vagas</a>
<a href="{% url 'core:update_candidato' %}" class="list-group-item">Alterar Dados</a>
<a href="{% url 'core:update_password_candidato' %}" class="list-group-item active" aria-current="page">Alterar Senha</a>
<a href="{% url 'core:curriculo_candidato' %}" class="list-group-item">Currículo</a>
{% endblock %}

{% block perfil_candidato_content %}
<h2>Alterar Senha</h2>
<hr>
<div>
  <form class="form-group" method="POST">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
        <span class="help-block">{{ error }}</span>
        {% endfor %}
      {% endfor %} 
      </div>
      <button type="submit" class="btn btn-outline-info">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}

core/templates/core/update_password_gestor.html
{% extends "core/perfil.html" %}
{% load widget_tweaks %}

{% block title_perfil_gestor_content %}
<li class="breadcrumb-item active" aria-current="page">Alterar Senha</li>
{% endblock %}

{% block breadcrumb_perfil_gestor_content %}
<a href="{% url 'core:perfil' %}" class="list-group-item">Minha Conta</a>
<a href="{% url 'core:vagas_gestor' %}" class="list-group-item">Gerenciar Vagas</a>
<a href="{% url 'core:update_gestor' %}" class="list-group-item">Alterar Dados</a>
<a href="{% url 'core:update_password_gestor' %}" class="list-group-item active" aria-current="page">Alterar Senha</a>
<a href="{% url 'core:cadastro_gestor' %}" class="list-group-item">Cadastrar Pessoa</a>
{% endblock %}

{% block perfil_gestor_content %}
<h2>Alterar Senha</h2>
<hr>
<div>
  <form class="form-group" method="POST">
    {% csrf_token %}
    <fieldset>
      {% for field in form %}
      <div class="form-group">
        <label for="{{ field.auto_id }}">{{ field.label }}</label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
        <span class="help-block">{{ error }}</span>
        {% endfor %}
      {% endfor %} 
      </div>
      <button type="submit" class="btn btn-outline-info">Submit</button>
    </fieldset>
  </form>
</div>
{% endblock %}